# k8s/backend-hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2               # <-- ขั้นต่ำ 2 ตัว
  maxReplicas: 10              # <-- สูงสุด 10 ตัว
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # <-- ถ้า CPU > 50% จะเพิ่ม Pod อัตโนมัติ
